version: 1.0.{build}
build:
  verbosity: minimal
environment:
  COVERALLS_REPO_TOKEN:
    secure: 5ukdlQaxNLdCTQMqe0pDBOIrP56LXt8GwPA7mLk30INJaq0yZd947JVfXDVJSPl9
before_build:
- ps: Install-Package coveralls.net -Pre
after_test:
- ps: "$result = $LASTEXITCODE \n\n$coverageFilePath = Resolve-Path -path \"TestResults\\*\\*.coverage\" \n\n$coverageFilePath = $coverageFilePath.ToString()\n\nif(Test-Path .\\coverage.coveragexml){ rm .\\coverage.coveragexml }\n\n& \"C:\\Program Files (x86)\\Microsoft Visual Studio 14.0\\Team Tools\\Dynamic Code Coverage Tools\\CodeCoverage.exe\" analyze /output:coverage.coveragexml \"$coverageFilePath\"\n \n$coveralls = \"packages/coveralls.net.0.7.0-beta0001/tools/csmacnz.coveralls.exe\"\n \n& $coveralls --dynamiccodecoverage -i coverage.coveragexml --useRelativePaths\n \nif($result -ne 0){\n  exit $result\n}"